### ISSUE TITLE
slow shutdown

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#10]
After I click shutdown/restart and the output appears on the screen displaying the current service states during poweroff the system waits 1.30 minutes at/after precached monitor.

I wrote at/after because the service "precached monitor" exits quickly but the process after that "user shell 3" needs the whole 1.30 minutes to exit.

I will replace the service names above with the right once after my system finished calculating. I am not sure what the exact name was. But I suspect it has something to do with precached. Will restart. in a minute to look for the service names :)

**Comment by idnovic** [comment]
"Linux precess monitor and pre-caching daemon"
`A stop job is running for Session 3 of user idnovic (x / 1min 30s)`

**Comment by X3n0m0rph59** [comment]
There is a known thread-deadlock problem on exit of the daemon, that is triggered sometimes during system shutdown. Precached currently will be killed by systemd after 15 seconds have elapsed, when the system is shutting down.

> I wrote at/after because the service "precached monitor" exits quickly but the process after that "user shell 3" needs the whole 1.30 minutes to exit.

I too have seen this happen on my Fedora box, with and without precached running. I suspect that this will be hard to reproduce...

**Comment by idnovic** [comment]
I think it has to do the the 3rd part of precached. The user service.
Because when I boot to gdm and shutdown instead of login everything is perfect. 

`systemctl --user enable --now precached-trigger.service`

**Comment by idnovic** [comment]
I can live with it. Just 1.30 minutes seem long...

**Comment by X3n0m0rph59** [comment]
> I think it has to do the the 3rd part of precached. The user service.
Because when I boot to gdm and shutdown instead of login everything is perfect.
>
> `$ systemctl --user enable --now precached-trigger.service`
>
> I can live with it. Just 1.30 minutes seem long...

This clearly should not happen!

I will prepare a new build tomorrow, could you please try to disable the user service and the prime-caches-timer then (after you have installed the new build)?

`$ systemctl --user disable --now precached-trigger.service`
`$ sudo systemctl disable --now precached-prime-caches.timer`

Profile transition will then be done using a `.desktop` file that can be added to Gnome 3 autostart. The other two possibilities of profile transition (.timer and user service) will be kept for non-Gnome users.

## Background on precached modes-of-operation (profiles)

Currently precached discriminates between two distinct runtime profiles:
* BootUp
* UpAndRunning

During `BootUp`, no offline-prefetching will be done. When transitioning to `UpAndRunning`, offline-prefetching will be enabled.

**Comment by idnovic** [comment]
Okay I can try that out. But honestly I am just pointing fingers :) not sure whatever the the precached trigger is the culprit.

**Comment by idnovic** [comment]
I need to debug this. I deactivated all 3 precached services and I still have the timeout.

**Comment by idnovic** [comment]
In case you missed it on the other issue report, the slow shutdown happens even with precached disabled. So let it be as it is. No need to rewrite that part.

**Comment by idnovic** [comment]
precached just seems to be the last process before the 1.30 minutes timeout.
But they seem unrelated atm.

At least I can not reproduce it.

**Comment by idnovic** [comment]
[https://unix.stackexchange.com/questions/273876/a-stop-job-is-running-for-session-c2-of-user/297318#297318](url)

Still need to verify the suggested methods tomorrow.

**Comment by idnovic** [comment]
Well the newest version did fix my slow shutdown. It now takes just 1 second. To be honest after I had to wait now I am thinking maybe something is wrong this is damn fast :)
