### ISSUE TITLE
is precached supposed to preload iotrace files?

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#6]
`/var/lib/precached/iotrace/...`

I saw that precached cached files from the above location.
Is this okay/expected?

**Comment by X3n0m0rph59** [comment]
Yes! It is intentionally done this way, since we don't want to wait for the disk to fetch a trace log.
If the trace logs would not be cached, online-prefetching would not work as expected!

## Background
If precached detects a `fork()` and subsequent `exec()` system call, it will hash the new process' file name and its command line parameters, and then search all trace logs looking for this specific hash value. If such a trace log of a previous program execution does exist, precached will initiate a replay of this trace log. This won't be as effective as loading the process' files ahead of time, but it at least may help a little bit. Especially if said process does a lot of "disk read"-computation-"disk read"-computation... cycles, online-prefetching may improve the startup performance considerably.

Benchmark of LibreOffice Calc:
Loaded ahead of time: 4 major page faults
Loaded with precached online-prefetching enabled: 257 major page faults
Loaded without precached: 1323 major page faults

**Comment by idnovic** [comment]
Okay that makes sense.
